server:
  port: 8889
spring:
  application:
    name: ts-assurance-service
  cloud:
    consul:
      config:
        enabled: false
      discovery:
        instance-id: ${spring.application.name}-${server.port}-${random.int[1,99]}
        prefer-ip-address: true
        health-check-critical-timeout: 2m
      host: ${CONSUL_HOST:localhost}
      port: 8500
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: 5672
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: admin@123#
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/ts-assurance-service?createDatabaseIfNotExist=true
    username: root
    hikari:
      maximum-pool-size: 2
  jpa:
    hibernate:
      ddl-auto: update
security:
  authorization-rules:
    - paths: ["/api/v1/trainservice/trains"]
      method: "POST"
      authorities: ["ROLE_ADMIN"]
    - paths: ["/api/v1/trainservice/trains"]
      method: "PUT"
      authorities: ["ROLE_ADMIN"]
    - paths: ["/api/v1/trainservice/trains/*"]
      method: "DELETE"
      authorities: ["ROLE_ADMIN"]
    - paths: ["/actuator/health", "/api/v1/trainservice/**"]
      authorities: ["permitAll"]
    - paths:
        - "/swagger-ui.html"
        - "/webjars/**"
        - "/images/**"
        - "/configuration/**"
        - "/swagger-resources/**"
        - "/v2/**"
      authorities: ["permitAll"]