server:
  port: 8900
spring:
  application:
    name: ts-order-service
  cloud:
    consul:
      config:
        enabled: false
      discovery:
        instance-id:
          ${spring.application.name}-${server.port}-${random.int[1,99]}
        prefer-ip-address: true
        health-check-critical-timeout: 2m
      host: ${CONSUL_HOST:localhost}
      port: 8500
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: 5672
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: admin@123#
    url:
      jdbc:mysql://${MYSQL_HOST:localhost}:3306/ts-order-service?createDatabaseIfNotExist=true
    username: root
    hikari:
      maximum-pool-size: 2
  jpa:
    hibernate:
      ddl-auto: update
security:
  authorization-rules:
    - paths: ["/actuator/health"]
      authorities: ["permitAll"]
    - paths: ["/api/v1/userservice/users/*"]
      method: "DELETE"
      authorities: ["ROLE_ADMIN", "ROLE_USER"]
    - paths: ["/api/v1/userservice/users/**"]
      authorities: ["permitAll"]
    - paths:
        - "/api/v1/travelplanservice/**"
        - "/swagger-ui.html"
        - "/webjars/**"
        - "/images/**"
        - "/configuration/**"
        - "/swagger-resources/**"
        - "/v2/**"
      authorities: ["permitAll"]
    - paths: ["/api/v1/adminorderservice/**"]
      authorities: ["ROLE_ADMIN"]
    - paths: ["/api/v1/preserveservice/**"]
      authorities: ['ROLE_USER']
    - paths: ["/api/v1/preserveotherservice/**"]
      authorities: ["ROLE_ADMIN", "ROLE_USER"]
