server:
  port: 8904
spring:
  application:
    name: ts-route-service
  cloud:
    consul:
      config:
        enabled: false
      discovery:
        instance-id:
          ${spring.application.name}-${server.port}-${random.int[1,99]}
        prefer-ip-address: true
        health-check-critical-timeout: 2m
      host: ${CONSUL_HOST:localhost}
      port: 8500
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: 5672
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: admin@123#
    url:
      jdbc:mysql://${MYSQL_HOST:localhost}:3306/ts-route-service?createDatabaseIfNotExist=true
    username: root
    hikari:
      maximum-pool-size: 2
  jpa:
    hibernate:
      ddl-auto: update
security:
  authorization-rules:
    - paths: ["/actuator/health"]
      authorities: ["permitAll"]
    - paths: ["/api/v1/userservice/users/*"]
      method: "DELETE"
      authorities: ["ROLE_ADMIN", "ROLE_USER"]
    - paths: ["/api/v1/routeservice/routes"]
      method: "POST"
      authorities: ['authenticated']
    - paths: ["/api/v1/routeservice/routes/*"]
      method: "DELETE"
      authorities: ["ROLE_ADMIN"]
    - paths: ["/api/v1/routeservice/**"]
      authorities: ["permitAll"]
    - paths: ["/api/v1/userservice/users/**"]
      authorities: ["permitAll"]
    - paths:
        - "/swagger-ui.html"
        - "/webjars/**"
        - "/images/**"
        - "/configuration/**"
        - "/swagger-resources/**"
        - "/v2/**"
      authorities: ["permitAll"]
    - paths: ["/api/v1/executeservice/**"]
      authorities: ["ROLE_ADMIN", "ROLE_USER"]
    - paths: ["/api/v1/adminrouteservice/**"]
      authorities: ["ROLE_ADMIN"]
    - paths: ["/api/v1/assuranceservice/**"]
      authorities: ["ROLE_USER"]
